name: Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: false

  schedule:
    - cron: "21 07 * * 1"
    
jobs:

  build:
    name: ${{ matrix.branch }}_${{ matrix.arch }}
    runs-on: ${{ (matrix.arch == 'amd64' || matrix.arch == 'i386') && 'ubuntu-latest' || 'ubuntu-22.04-arm' }}
    strategy:
      matrix: 
        branch: >-
          ${{ fromJSON(github.event.inputs.branch && format('["{0}"]', github.event.inputs.branch) || 
                       '["linux-rolling-stable", "linux-rolling-lts", "linux-6.1.y"]') }}
        arch: ["amd64", "i386", "arm64", "armhf", "riscv64"]
        
    steps:
      - name: "free"
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: "env"
        run: |
          echo -e "DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          
          if [[ "${{ matrix.arch }}" == "amd64" ]]; then
            echo -e "MAKE_ENV=" >> ${GITHUB_ENV}
            echo -e "ARCH_DESC=\`amd64\` / \`x86-64\`" >> ${GITHUB_ENV}
          fi
          if [[ "${{ matrix.arch }}" == "i386" ]]; then
            echo -e "MAKE_ENV=ARCH=i386 CROSS_COMPILE=i686-linux-gnu-" >> ${GITHUB_ENV}
            echo -e "ARCH_DESC=\`i386\` / \`i686\` / \`ia32\` / \`x86\` / \`x86-32\`" >> ${GITHUB_ENV}
          fi
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            echo -e "MAKE_ENV=" >> ${GITHUB_ENV}
            echo -e "ARCH_DESC=\`arm64\` / \`aarch64\`" >> ${GITHUB_ENV}
          fi
          if [[ "${{ matrix.arch }}" == "armhf" ]]; then
            echo -e "MAKE_ENV=ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- KBUILD_DEBARCH=armhf" >> ${GITHUB_ENV}
            echo -e "ARCH_DESC=\`armhf\` / \`armv7\` / \`arm\` / \`arm32\` / \`aarch32\` (hard-float)" >> ${GITHUB_ENV}
          fi
          if [[ "${{ matrix.arch }}" == "riscv64" ]]; then
            echo -e "MAKE_ENV=ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu-" >> ${GITHUB_ENV}
            echo -e "ARCH_DESC=\`riscv64\`" >> ${GITHUB_ENV}
          fi

          if [[ "${{ matrix.branch }}" == "linux-rolling-stable" ]]; then
            echo -e "BRANCH_DESC=stable" >> ${GITHUB_ENV}
          elif [[ "${{ matrix.branch }}" == "linux-rolling-lts" ]]; then
            echo -e "BRANCH_DESC=LTS" >> ${GITHUB_ENV}
          elif [[ "${{ matrix.branch }}" == "linux-6.1.y" ]]; then
            echo -e "BRANCH_DESC=6.1 LTS" >> ${GITHUB_ENV}
          else
            echo -e "BRANCH_DESC=${{ matrix.branch }}" >> ${GITHUB_ENV}
          fi
      
      - name: "checkout"
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.branch == 'v3' && github.repository || 'gregkh/linux' }}
          ref: ${{ matrix.branch }}
          fetch-depth: ${{ matrix.branch == 'v3' && 1 || 0 }}

      - name: "patch"
        if: ${{ matrix.branch != 'v3' }}
        run: |
          curl -LO "https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/build/patches/${{ matrix.branch }}.patch"
          git apply -3 ${{ matrix.branch }}.patch

      - name: "dependencies"
        run: |
          sudo dpkg --add-architecture ${{ matrix.arch }}
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper-compat=12 libelf-dev bc libdw-dev
          sudo apt-get install -y crossbuild-essential-${{ matrix.arch }}
          sudo apt-get install -y libssl-dev:${{ matrix.arch }}
          sudo apt-get clean
          sudo apt-get autoremove
        
      - name: "configure"
        run: |
          make ${{ env.MAKE_ENV }} olddefconfig

      - name: "tag"
        run: |
          KERNEL_VER=$(make kernelversion)
          TAG_NAME=linux-$KERNEL_VER-bbr3-${{ matrix.arch }}
          TAG_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" "https://api.github.com/repos/${{ github.repository }}/git/ref/tags/$TAG_NAME" | grep -q '^200$' && echo true || echo false)
          echo -e "KERNEL_VER=$KERNEL_VER" >> ${GITHUB_ENV}
          echo -e "TAG_NAME=$TAG_NAME" >> ${GITHUB_ENV}
          echo -e "TAG_EXISTS=$TAG_EXISTS" >> ${GITHUB_ENV}
      
      - name: "make"
        if: ${{ env.TAG_EXISTS == 'false' }}
        run: |
          make ${{ env.MAKE_ENV }} -j$(nproc) bindeb-pkg LOCALVERSION=-bbr3 KDEB_PKGVERSION=${{ env.KERNEL_VER }}-bbr3
      
      - name: "release"
        if: ${{ env.TAG_EXISTS == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ matrix.arch == 'amd64' }}
          prerelease: false
          make_latest: false
          files: ../linux-*.deb
          target_commitish: ${{ matrix.branch == 'v3' && matrix.branch || 'build' }}
          tag_name: ${{ env.TAG_NAME }}
          name: "Linux ${{ env.KERNEL_VER }} BBR-v3 ${{ matrix.arch }}"
          fail_on_unmatched_files: true
          overwrite_files: true
          generate_release_notes: false
          append_body: false
          body: |-
            **Target Architecture:** ${{ env.ARCH_DESC }}
            
            ${{ matrix.arch == 'amd64' && format('This is the *latest {0} kernel* released on 20XX-XX-XX.', env.BRANCH_DESC) || '' }}
            ${{ format('See [this release](https://github.com/XDflight/bbr3-debs/releases/tag/linux-{0}-bbr3-amd64) for {1}.', 
                       matrix.arch != 'amd64' && env.KERNEL_VER || 'X.X.X', 
                       matrix.arch == 'amd64' && 'more information' || 'detailed release notes') }}
